:wrench: added profiles to laravel stop restart and down

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.3 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -533,7 +533,7 @@ ez_laravel_stop_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel stop\n"
+  printf "  ez laravel stop APP_ENV\n"
   printf "  ez laravel stop --help | -h\n"
   echo
 
@@ -544,6 +544,15 @@ ez_laravel_stop_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -565,7 +574,7 @@ ez_laravel_restart_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel restart\n"
+  printf "  ez laravel restart APP_ENV\n"
   printf "  ez laravel restart --help | -h\n"
   echo
 
@@ -576,6 +585,15 @@ ez_laravel_restart_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -597,7 +615,7 @@ ez_laravel_down_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel down\n"
+  printf "  ez laravel down APP_ENV\n"
   printf "  ez laravel down --help | -h\n"
   echo
 
@@ -608,6 +626,15 @@ ez_laravel_down_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -832,12 +859,16 @@ ez_all_down_usage() {
 }
 
 # :command.normalize_input
+# :command.normalize_input_function
 normalize_input() {
-  local arg flags
+  local arg flags passthru
+  passthru=false
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -848,6 +879,9 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -855,12 +889,15 @@ normalize_input() {
     shift
   done
 }
+
 # :command.inspect_args
 inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
   else
     echo args: none
   fi
@@ -878,9 +915,19 @@ inspect_args() {
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
     echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
   fi
 
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
 }
 
 # :command.user_lib
@@ -1193,6 +1240,7 @@ ez_laravel_deploy_command() {
   merge_env $base_env $override_env $merged_env
   #TODO merge read_env and merge_env fn and process all env in before.sh?
 
+  #FIXME on first run this will fail since db is not fully up and functional yet
   create_new_database_and_user $DB_DATABASE $DB_USERNAME $DB_PASSWORD
 
   log_header "Running Docker Compose for Laravel $APP_ENV"
@@ -2036,8 +2084,8 @@ ez_laravel_deploy_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['APP_ENV']+x} ]]; then
-
           args['APP_ENV']=$1
           shift
         else
@@ -2098,8 +2146,8 @@ ez_laravel_start_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['APP_ENV']+x} ]]; then
-
           args['APP_ENV']=$1
           shift
         else
@@ -2160,13 +2208,31 @@ ez_laravel_stop_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        # :argument.case
+        if [[ -z ${args['APP_ENV']+x} ]]; then
+          args['APP_ENV']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['APP_ENV']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez laravel stop APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['APP_ENV']:-} ]] && [[ ! ${args['APP_ENV']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "APP_ENV must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
@@ -2204,13 +2270,31 @@ ez_laravel_restart_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        # :argument.case
+        if [[ -z ${args['APP_ENV']+x} ]]; then
+          args['APP_ENV']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['APP_ENV']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez laravel restart APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['APP_ENV']:-} ]] && [[ ! ${args['APP_ENV']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "APP_ENV must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
@@ -2248,13 +2332,31 @@ ez_laravel_down_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        # :argument.case
+        if [[ -z ${args['APP_ENV']+x} ]]; then
+          args['APP_ENV']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['APP_ENV']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez laravel down APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['APP_ENV']:-} ]] && [[ ! ${args['APP_ENV']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "APP_ENV must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
@@ -2387,8 +2489,8 @@ ez_all_deploy_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['APP_ENV']+x} ]]; then
-
           args['APP_ENV']=$1
           shift
         else
@@ -2449,8 +2551,8 @@ ez_all_start_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['APP_ENV']+x} ]]; then
-
           args['APP_ENV']=$1
           shift
         else
@@ -2643,6 +2745,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
