:arrow_up_small: WIP laravel deploy

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -445,7 +445,7 @@ ez_laravel_deploy_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel deploy APP_ENV\n"
+  printf "  ez laravel deploy APP_NAME APP_ENV\n"
   printf "  ez laravel deploy --help | -h\n"
   echo
 
@@ -460,6 +460,11 @@ ez_laravel_deploy_usage() {
 
     # :command.usage_args
     printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_NAME"
+    printf "    Laravel app name\n"
+    echo
 
     # :argument.usage
     printf "  %s\n" "APP_ENV"
@@ -486,7 +491,7 @@ ez_laravel_start_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel start APP_ENV\n"
+  printf "  ez laravel start APP_NAME APP_ENV\n"
   printf "  ez laravel start --help | -h\n"
   echo
 
@@ -501,6 +506,11 @@ ez_laravel_start_usage() {
 
     # :command.usage_args
     printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_NAME"
+    printf "    Laravel app name\n"
+    echo
 
     # :argument.usage
     printf "  %s\n" "APP_ENV"
@@ -524,7 +534,7 @@ ez_laravel_stop_usage() {
   fi
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel stop\n"
+  printf "  ez laravel stop APP_NAME APP_ENV\n"
   printf "  ez laravel stop --help | -h\n"
   echo
 
@@ -535,6 +545,20 @@ ez_laravel_stop_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_NAME"
+    printf "    Laravel app name\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -556,7 +580,7 @@ ez_laravel_restart_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel restart\n"
+  printf "  ez laravel restart APP_NAME APP_ENV\n"
   printf "  ez laravel restart --help | -h\n"
   echo
 
@@ -567,6 +591,20 @@ ez_laravel_restart_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_NAME"
+    printf "    Laravel app name\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -585,7 +623,7 @@ ez_laravel_down_usage() {
   fi
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel down\n"
+  printf "  ez laravel down APP_NAME APP_ENV\n"
   printf "  ez laravel down --help | -h\n"
   echo
 
@@ -596,6 +634,20 @@ ez_laravel_down_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_NAME"
+    printf "    Laravel app name\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -1110,31 +1162,28 @@ ez_laravel_deploy_command() {
   # src/laravel_deploy_command.sh
   inspect_args
 
-  log_header "Preparing to deploy Laravel in $APP_ENV mode"
+  log_header "Preparing to deploy Laravel in ${args[APP_ENV]} mode"
 
-  #TODO improve here i have duplication in app_env arg and APP_ENV in .env files
-  #load_env "env/.env"
-  #load_env "env/docker.env"
+  #TODO check if env files exist?
+  app_dir="data/${args[APP_NAME]}"
 
-  #if [[ -n "${args[APP_ENV]}" ]]; then
-  #  load_env "env/${args[APP_ENV]}.env"
-  #fi
+  laravel_env_path="$app_dir/env/laravel.env"
+  override_env_path="$app_dir/env/${args[APP_ENV]}.env"
+  merged_env_path="$app_dir/env/merged/${args[APP_ENV]}.env"
 
-  #if [[ "$APP_ENV" != "${args[APP_ENV]}" ]]; then
-  #    log_error "Error: APP_ENV in 'env/${args[APP_ENV]}.env' does not match 'ez' command argument ('$APP_ENV'!='${args[APP_ENV]}')."
-  #    exit 1
-  #fi
+  merge_env "$laravel_env_path" "$override_env_path" "$merged_env_path"
 
-  #careful with laravel_folder_name, it must be the same as laravel dockerfile and docker compose file
-  laravel_folder_name="laravel-$APP_ENV"
+  load_env "config/docker.env"
+  load_env "$merged_env_path"
+
+  SOURCE_CODE_DIR="$app_dir/src-$APP_ENV"
   #TODO maybe skip if nothing was changed?
-  # Check if the folder exists
-  #TODO add a force clone config somewhere so user can choose to always clone instead of updating the repo
+  #TODO add a force clone config somewhere so user can choose to always clone instead of updating the repo?
   log_header "Preparing source code"
-  if [ -d "$laravel_folder_name" ]; then
-      log "Updating existing $laravel_folder_name folder"
+  if [ -d "$SOURCE_CODE_DIR" ]; then
+      log "Updating existing $SOURCE_CODE_DIR folder"
 
-      cd "$laravel_folder_name" || exit 1
+      cd "$SOURCE_CODE_DIR" || exit 1
 
       log "Removing previous build folders..."
       rm -rf "node_modules" "vendor" "public/build"
@@ -1153,8 +1202,8 @@ ez_laravel_deploy_command() {
 
       cd - || exit 1
   else
-      log "Cloning new $laravel_folder_name folder"
-      git clone --depth 1 -b "$GIT_BRANCH" "$GIT_URL" "$laravel_folder_name"
+      log "Cloning new $SOURCE_CODE_DIR folder"
+      git clone --depth 1 -b "$GIT_BRANCH" "$GIT_URL" "$SOURCE_CODE_DIR"
 
       # Check if cloning was successful
       if [ $? -ne 0 ]; then
@@ -1163,18 +1212,11 @@ ez_laravel_deploy_command() {
       fi
   fi
 
-  #TODO check if env files exist?
-  base_env="env/.env"
-  override_env="env/$APP_ENV.env"
-  merged_env="env/merged/$APP_ENV.env"
-  merge_env $base_env $override_env $merged_env
-  #TODO merge read_env and merge_env fn and process all env in before.sh?
-
-  #FIXME on first run this will fail since db is not fully up and functional yet
-  create_new_database_and_user $DB_DATABASE $DB_USERNAME $DB_PASSWORD
+  #FIXME on first run this will fail since db is not fully up and functional yet, fix with healthcheck?
+  create_new_database_and_user "$DB_DATABASE" "$DB_USERNAME" "$DB_PASSWORD"
 
   log_header "Running Docker Compose for Laravel $APP_ENV"
-  docker compose -f compose-laravel.yml --profile "$APP_ENV" --env-file "$merged_env" up --build -d
+  docker compose -f compose-laravel.yml --profile "$APP_ENV" --env-file "$merged_env_path" up --build -d
 
 }
 
@@ -1227,37 +1269,35 @@ ez_laravel_new_command() {
   APP_NAME=$(echo "$ENV_CONTENT" | grep -oP '^APP_NAME=\K.*')
   APP_NAME=$(ask_question "Enter the application name" "$APP_NAME")
 
-  DATA_DIR="data/$APP_NAME"
+  APP_DIR="data/$APP_NAME"
 
-  if [[ -d "$DATA_DIR" ]]; then
-      log_error "Directory $DATA_DIR already exists app_name must be unique."
+  if [[ -d "$APP_DIR" ]]; then
+      log_error "Directory $APP_DIR already exists app_name must be unique."
       exit 1
   fi
 
-  log "Creating $DATA_DIR directory"
-  mkdir -p "$DATA_DIR/env/generated"
+  log "Creating $APP_DIR directory"
+  mkdir -p "$APP_DIR/env/generated"
 
-  COPY_ENV_TO="$DATA_DIR/env/laravel.env"
-
-  log "saving .env file into $COPY_ENV_TO"
-  echo "$ENV_CONTENT" > "$COPY_ENV_TO"
+  log "saving .env file into $APP_DIR/env/laravel.env"
+  echo "$ENV_CONTENT" > "$APP_DIR/env/laravel.env"
 
   log_info "Git url examples:"
   log "normal git url (you get prompted for authorization): https://github.com/MansourM/ez-docker-for-laravel.git"
   log "or this format: https://<user>:<pass>@github.com/MansourM/ez-docker-for-laravel.git"
   GIT_URL=$(ask_question "Enter the application git url" "https://github.com/MansourM/ez-docker-for-laravel-example.git")
 
-  cat <<EOL > "$DATA_DIR/env/app.env"
+  cat <<EOL > "$APP_DIR/env/app.env"
 GIT_URL=$GIT_URL
 EOL
 
-  SETUP_TEST_ENV=$(ask_question "Do you want to set up the test environment?" "yes")
+  SETUP_TEST_ENV=$(ask_question "Do you want to set up the test environment?" "no")
 
   if [[ "$SETUP_TEST_ENV" == "yes" || "$SETUP_TEST_ENV" == "y" ]]; then
     setup_environment "$APP_NAME" "test"
   fi
 
-  SETUP_STAGING_ENV=$(ask_question "Do you want to set up the staging environment?" "yes")
+  SETUP_STAGING_ENV=$(ask_question "Do you want to set up the staging environment?" "no")
 
   if [[ "$SETUP_STAGING_ENV" == "yes" || "$SETUP_TEST_ENV" == "y" ]]; then
     setup_environment "$APP_NAME" "staging"
@@ -2023,7 +2063,11 @@ ez_laravel_deploy_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         # :argument.case
-        if [[ -z ${args['APP_ENV']+x} ]]; then
+        if [[ -z ${args['APP_NAME']+x} ]]; then
+          args['APP_NAME']=$1
+          shift
+        # :argument.case
+        elif [[ -z ${args['APP_ENV']+x} ]]; then
           args['APP_ENV']=$1
           shift
         else
@@ -2037,8 +2081,12 @@ ez_laravel_deploy_parse_requirements() {
   done
 
   # :command.required_args_filter
+  if [[ -z ${args['APP_NAME']+x} ]]; then
+    printf "missing required argument: APP_NAME\nusage: ez laravel deploy APP_NAME APP_ENV\n" >&2
+    exit 1
+  fi
   if [[ -z ${args['APP_ENV']+x} ]]; then
-    printf "missing required argument: APP_ENV\nusage: ez laravel deploy APP_ENV\n" >&2
+    printf "missing required argument: APP_ENV\nusage: ez laravel deploy APP_NAME APP_ENV\n" >&2
     exit 1
   fi
 
@@ -2085,7 +2133,11 @@ ez_laravel_start_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         # :argument.case
-        if [[ -z ${args['APP_ENV']+x} ]]; then
+        if [[ -z ${args['APP_NAME']+x} ]]; then
+          args['APP_NAME']=$1
+          shift
+        # :argument.case
+        elif [[ -z ${args['APP_ENV']+x} ]]; then
           args['APP_ENV']=$1
           shift
         else
@@ -2099,8 +2151,12 @@ ez_laravel_start_parse_requirements() {
   done
 
   # :command.required_args_filter
+  if [[ -z ${args['APP_NAME']+x} ]]; then
+    printf "missing required argument: APP_NAME\nusage: ez laravel start APP_NAME APP_ENV\n" >&2
+    exit 1
+  fi
   if [[ -z ${args['APP_ENV']+x} ]]; then
-    printf "missing required argument: APP_ENV\nusage: ez laravel start APP_ENV\n" >&2
+    printf "missing required argument: APP_ENV\nusage: ez laravel start APP_NAME APP_ENV\n" >&2
     exit 1
   fi
 
@@ -2146,13 +2202,39 @@ ez_laravel_stop_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        # :argument.case
+        if [[ -z ${args['APP_NAME']+x} ]]; then
+          args['APP_NAME']=$1
+          shift
+        # :argument.case
+        elif [[ -z ${args['APP_ENV']+x} ]]; then
+          args['APP_ENV']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['APP_NAME']+x} ]]; then
+    printf "missing required argument: APP_NAME\nusage: ez laravel stop APP_NAME APP_ENV\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['APP_ENV']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez laravel stop APP_NAME APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['APP_ENV']:-} ]] && [[ ! ${args['APP_ENV']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "APP_ENV must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
@@ -2190,13 +2272,39 @@ ez_laravel_restart_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        # :argument.case
+        if [[ -z ${args['APP_NAME']+x} ]]; then
+          args['APP_NAME']=$1
+          shift
+        # :argument.case
+        elif [[ -z ${args['APP_ENV']+x} ]]; then
+          args['APP_ENV']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['APP_NAME']+x} ]]; then
+    printf "missing required argument: APP_NAME\nusage: ez laravel restart APP_NAME APP_ENV\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['APP_ENV']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez laravel restart APP_NAME APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['APP_ENV']:-} ]] && [[ ! ${args['APP_ENV']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "APP_ENV must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
@@ -2234,13 +2342,39 @@ ez_laravel_down_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        # :argument.case
+        if [[ -z ${args['APP_NAME']+x} ]]; then
+          args['APP_NAME']=$1
+          shift
+        # :argument.case
+        elif [[ -z ${args['APP_ENV']+x} ]]; then
+          args['APP_ENV']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['APP_NAME']+x} ]]; then
+    printf "missing required argument: APP_NAME\nusage: ez laravel down APP_NAME APP_ENV\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['APP_ENV']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez laravel down APP_NAME APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['APP_ENV']:-} ]] && [[ ! ${args['APP_ENV']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "APP_ENV must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
