:new: WIP exploring

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -34,6 +34,7 @@ ez_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
+  printf "  %s   test cmd\n" "test   "
   printf "  %s   Docker Commands\n" "docker "
   printf "  %s   Shared containers Commands\n" "shared "
   printf "  %s   Laravel containers Commands\n" "laravel"
@@ -55,6 +56,74 @@ ez_usage() {
     printf "%s\n" "Examples:"
     printf "  ez docker install\n"
     printf "  ez d i\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+ez_test_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "ez test - test cmd\n"
+    echo
+
+  else
+    printf "ez test - test cmd\n"
+    echo
+
+  fi
+
+  printf "Alias: t\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  ez test COMMAND\n"
+  printf "  ez test [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "Commands:"
+  printf "  %s   add docker repository to apt sources, then install docker engine\n" "install"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+ez_test_install_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "ez test install - add docker repository to apt sources, then install docker engine\n"
+    echo
+
+  else
+    printf "ez test install - add docker repository to apt sources, then install docker engine\n"
+    echo
+
+  fi
+
+  printf "Alias: i\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  ez test install\n"
+  printf "  ez test install --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -1102,6 +1171,289 @@ read_multi_line_input() {
     echo "$result"
 }
 
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# ez completion                                            -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_ez_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_ez_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'docker uninstall\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel restart\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'docker install\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel deploy\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'shared restart\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'shared deploy\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel start\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'docker remove\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'test install\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "$(ls -d apps/*/ 2>/dev/null | xargs -n 1 basename) --help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'shared start\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel stop\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel down\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'shared stop\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'shared down\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'d uninstall\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel new\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel s\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l restart\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel n\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s restart\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel d\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'t install\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "$(ls -d apps/*/ 2>/dev/null | xargs -n 1 basename) --help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'d install\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel r\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'shared d\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s deploy\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'d remove\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'docker r\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'shared s\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'docker u\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'shared r\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'docker i\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l deploy\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l start\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s start\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'laravel\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h d deploy down n new r restart s start stop")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'test i\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "$(ls -d apps/*/ 2>/dev/null | xargs -n 1 basename) --help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l stop\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s down\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s stop\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l down\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'shared\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h d deploy down r restart s start stop")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'docker\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h i install r remove u uninstall")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l new\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'test\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h i install")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'d i\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l d\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'d r\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l s\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'t i\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "$(ls -d apps/*/ 2>/dev/null | xargs -n 1 basename) --help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s d\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s r\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l n\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'d u\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l r\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h production staging test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s s\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h d deploy down r restart s start stop")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'d\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h i install r remove u uninstall")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'t\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h i install")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'l\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help -h d deploy down n new r restart s start stop")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_ez_completions_filter "--help --version -h -v d docker l laravel s shared t test")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _ez_completions ez'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # src/lib/setup_environment.sh
 setup_environment() {
   local app_name=$1
@@ -1147,6 +1499,18 @@ EOL
 }
 
 # :command.command_functions
+
+# :command.function
+ez_test_install_command() {
+  # src/test_install_command.sh
+  echo "# this file is located in 'src/test_install_command.sh'"
+  echo "# code for 'ez test install' goes here"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
+
+  echo "test install"
+
+}
 
 # :command.function
 ez_docker_install_command() {
@@ -1489,6 +1853,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    test | t)
+      action="test"
+      shift
+      ez_test_parse_requirements "$@"
+      shift $#
+      ;;
+
     docker | d)
       action="docker"
       shift
@@ -1522,6 +1893,117 @@ parse_requirements() {
       ;;
 
   esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+ez_test_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        ez_test_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    install | i)
+      action="install"
+      shift
+      ez_test_install_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      ez_test_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+ez_test_install_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        ez_test_install_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="test install"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2573,12 +3055,15 @@ ez_laravel_new_parse_requirements() {
 # :command.user_hooks
 before_hook() {
   # src/before.sh
-  #inspect_args
+  inspect_args
 
-  if [[ $EUID -ne 0 ]]; then
-     log_error "This script must be run as root"
-     exit 1
-  fi
+  eval "$(send_completions)"
+
+  #if [[ $EUID -ne 0 ]]; then
+  #   log_error "This script must be run as root"
+  #   exit 1
+  #fi
+
 }
 
 # :command.initialize
@@ -2601,6 +3086,8 @@ run() {
   before_hook
 
   case "$action" in
+    "test") ez_test_command ;;
+    "test install") ez_test_install_command ;;
     "docker") ez_docker_command ;;
     "docker install") ez_docker_install_command ;;
     "docker uninstall") ez_docker_uninstall_command ;;
