:arrow_up_small: right now APP_ENV in laravel .env file should match the command argument, added a guard clause to check it

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -2623,6 +2623,11 @@ before_hook() {
     read_env "env/${args[APP_ENV]}.env"
   fi
 
+  if [[ "$APP_ENV" != "${args[APP_ENV]}" ]]; then
+      log_error "Error: APP_ENV in 'env/${args[APP_ENV]}.env' does not match command argument ('$APP_ENV'!='${args[APP_ENV]}')."
+      exit 1
+  fi
+
 }
 
 # :command.initialize
