:arrow_up_small: WIP laravel deploy

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -1108,8 +1108,22 @@ ez_shared_down_command() {
 # :command.function
 ez_laravel_deploy_command() {
   # src/laravel_deploy_command.sh
-  #TODO duplication, read APP_ENV from cli args and ignore APP_ENV in .env?
+  inspect_args
+
   log_header "Preparing to deploy Laravel in $APP_ENV mode"
+
+  #TODO improve here i have duplication in app_env arg and APP_ENV in .env files
+  #load_env "env/.env"
+  #load_env "env/docker.env"
+
+  #if [[ -n "${args[APP_ENV]}" ]]; then
+  #  load_env "env/${args[APP_ENV]}.env"
+  #fi
+
+  #if [[ "$APP_ENV" != "${args[APP_ENV]}" ]]; then
+  #    log_error "Error: APP_ENV in 'env/${args[APP_ENV]}.env' does not match 'ez' command argument ('$APP_ENV'!='${args[APP_ENV]}')."
+  #    exit 1
+  #fi
 
   #careful with laravel_folder_name, it must be the same as laravel dockerfile and docker compose file
   laravel_folder_name="laravel-$APP_ENV"
@@ -2281,21 +2295,6 @@ before_hook() {
      log_error "This script must be run as root"
      exit 1
   fi
-
-  #TODO improve here i have duplication in app_env arg and APP_ENV in .env files
-  #log_header "Reading .env files"
-  #load_env "env/.env"
-  #load_env "env/docker.env"
-
-  #if [[ -n "${args[APP_ENV]}" ]]; then
-  #  load_env "env/${args[APP_ENV]}.env"
-  #fi
-
-  #if [[ "$APP_ENV" != "${args[APP_ENV]}" ]]; then
-  #    log_error "Error: APP_ENV in 'env/${args[APP_ENV]}.env' does not match 'ez' command argument ('$APP_ENV'!='${args[APP_ENV]}')."
-  #    exit 1
-  #fi
-
 }
 
 # :command.initialize
