:bug: bugfix Remove leading and trailing whitespaces, and carriage return when reading .env files

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -924,6 +924,45 @@ read_env() {
   echo ""
 }
 
+# src/lib/read_env_ne.sh
+read_env_ne() {
+  local filePath="${1:-.env}"
+
+  if [ ! -f "$filePath" ]; then
+    echo "missing ${filePath}"
+    exit 1
+  fi
+
+  echo -e "\n==[ Reading $filePath ]==\n"
+  while IFS= read -r LINE; do
+    # Remove leading and trailing whitespaces, and carriage return
+    CLEANED_LINE=$(echo "$LINE" | awk '{$1=$1};1' | tr -d '\r')
+
+    if [[ $CLEANED_LINE != '#'* ]] && [[ $CLEANED_LINE == *'='* ]]; then
+      echo "$CLEANED_LINE"
+      export "$CLEANED_LINE"
+    fi
+  done < "$filePath"
+  echo ""
+}
+
+# src/lib/read_env_new.sh
+read_env_new() {
+
+  local filePath="${1:-.env}"
+
+  if [ ! -f "$filePath" ]; then
+    echo "missing ${filePath}"
+    exit 1
+  fi
+
+  echo -e "\n==[ Reading $filePath ]==\n"
+
+  awk -F= '/^[^#]/ && /=/ { gsub(/^[ \t]+|[ \t\r]+$/, "", $1); gsub(/^[ \t]+|[ \t\r]+$/, "", $2); export $1=$2 }' "$filePath"
+
+  echo ""
+}
+
 # :command.command_functions
 
 # :command.function
@@ -1048,11 +1087,6 @@ ez_shared_down_command() {
 ez_laravel_deploy_command() {
   # src/laravel_deploy_command.sh
   #TODO duplication read APP_ENV from cli args and ignore APP_ENV in .env?
-  if [[ "$APP_ENV" != "test" && "$APP_ENV" != "staging" && "$APP_ENV" != "production" ]]; then
-      echo "Error: Invalid value for APP_ENV. It must be either test, staging, or production."
-      exit 1
-  fi
-
   echo "Preparing to deploy Laravel in $APP_ENV mode."
 
   #careful with laravel_folder_name, it must be the same as laravel dockerfile and docker compose file
@@ -2533,14 +2567,14 @@ before_hook() {
   # src/before.sh
   inspect_args
 
-  read_env "env/.env"
+  read_env_ne "env/.env"
 
   #TODO improve here i have duplication in app_env arg and APP_ENV in .env files
   if [[ -z "${args[APP_ENV]}" ]]; then
           echo "Error: 'APP_ENV' is not set or empty. Please set a valid argument." >&2
           exit 1
   fi
-  read_env "env/${args[APP_ENV]}.env"
+  read_env_ne "env/${args[APP_ENV]}.env"
 
 }
 
