:arrow_up_small: WIP

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.2 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.3 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -50,14 +50,6 @@ ez_usage() {
     echo
     printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
-    echo
-
-    # :command.usage_environment_variables
-    printf "%s\n" "Environment Variables:"
-
-    # :environment_variable.usage
-    printf "  %s\n" "API_KEY"
-    printf "    Set your API key\n"
     echo
 
     # :command.usage_examples
@@ -459,7 +451,7 @@ ez_laravel_deploy_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel deploy\n"
+  printf "  ez laravel deploy APP_ENV\n"
   printf "  ez laravel deploy --help | -h\n"
   echo
 
@@ -470,6 +462,15 @@ ez_laravel_deploy_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -491,7 +492,7 @@ ez_laravel_start_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez laravel start\n"
+  printf "  ez laravel start APP_ENV\n"
   printf "  ez laravel start --help | -h\n"
   echo
 
@@ -502,6 +503,15 @@ ez_laravel_start_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -659,7 +669,7 @@ ez_all_deploy_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez all deploy\n"
+  printf "  ez all deploy APP_ENV\n"
   printf "  ez all deploy --help | -h\n"
   echo
 
@@ -670,6 +680,15 @@ ez_all_deploy_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -691,7 +710,7 @@ ez_all_start_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  ez all start\n"
+  printf "  ez all start APP_ENV\n"
   printf "  ez all start --help | -h\n"
   echo
 
@@ -702,6 +721,15 @@ ez_all_start_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "APP_ENV"
+    printf "    Laravel app environment\n"
+    printf "    Allowed: test, staging, production\n"
     echo
 
   fi
@@ -856,29 +884,6 @@ inspect_args() {
 }
 
 # :command.user_lib
-# src/lib/copy_file.sh
-# Define a function for copying files and checking errors
-copy_file() {
-    local source_file=$1
-    local target_dir=$2
-    local target_file=$3
-
-    echo "Copying $source_file to $target_dir folder..."
-    if [ -f "$source_file" ]; then
-        cp "$source_file" "$target_dir/$target_file"
-        chmod +x "$target_dir/$target_file"
-
-        # Check if file copying was successful
-        if [ $? -ne 0 ]; then
-            echo "Error: Failed to copy $source_file."
-            exit 1
-        fi
-    else
-        echo "Error: $source_file not found."
-        exit 1
-    fi
-}
-
 # src/lib/merge_env.sh
 merge_env() {
   local file1="$1"
@@ -1042,10 +1047,9 @@ ez_laravel_deploy_command() {
   # src/laravel_deploy_command.sh
   #inspect_args
 
-  #TODO read APP_ENV from cli args and ignore APP_ENV in .env?
-  # Check if APP_ENV is set to dev, test, staging, or production
-  if [[ "$APP_ENV" != "dev" && "$APP_ENV" != "test" && "$APP_ENV" != "staging" && "$APP_ENV" != "production" ]]; then
-      echo "Error: Invalid value for APP_ENV. It must be either dev, test, staging, or production."
+  #TODO duplication read APP_ENV from cli args and ignore APP_ENV in .env?
+  if [[ "$APP_ENV" != "test" && "$APP_ENV" != "staging" && "$APP_ENV" != "production" ]]; then
+      echo "Error: Invalid value for APP_ENV. It must be either test, staging, or production."
       exit 1
   fi
 
@@ -1061,7 +1065,8 @@ ez_laravel_deploy_command() {
       cd "$laravel_folder_name" || exit 1
       echo "Remove previous build folders..."
       rm -rf "node_modules" "vendor" "public/build"
-
+      echo "Discard local changes"
+      git reset --hard
       git pull origin "$APP_ENV"
 
       # Check if the git operation was successful
@@ -1089,17 +1094,28 @@ ez_laravel_deploy_command() {
   fi
 
   # Copy necessary files to the Laravel folder
-  #TODO separate .env file for each environment?
-  copy_file ".env" "$laravel_folder_name" ".env"
-  copy_file "entrypoint-builder-$APP_ENV.sh" "$laravel_folder_name" "entrypoint-builder.sh"
-  copy_file "entrypoint-laravel.sh" "$laravel_folder_name" "entrypoint-laravel.sh"
+  env_laravel="config/.env"
+  entrypoint_laravel="entrypoint/nginx-fpm-laravel.sh"
+  env_override="config/$APP_ENV.env"
+  entrypoint_builder="entrypoint/builder-production.sh"
+  if [[ "$APP_ENV" == "test" ]]; then
+      entrypoint_builder="entrypoint/builder-test.sh"
+  fi
+
+  cp "$env_laravel" "$laravel_folder_name/.env"
+
+  cp "$entrypoint_builder" "$laravel_folder_name/entrypoint-builder.sh"
+  chmod +x "$laravel_folder_name/entrypoint-builder.sh"
+
+  cp "$entrypoint_laravel" "$laravel_folder_name/entrypoint.sh"
+  chmod +x "$laravel_folder_name/entrypoint.sh"
 
   # Run Docker Compose
   echo "Running Docker Compose for builder..."
-  docker compose -f compose-builder.yml --profile "$APP_ENV" up --build
+  docker compose -f compose-builder.yml --profile "$APP_ENV" --env-file "$env_laravel" --env-file "$env_override" up --build
 
   echo "Running Docker Compose for Laravel in detached mode..."
-  docker compose -f compose-laravel.yml --profile "$APP_ENV" up --build -d
+  docker compose -f compose-laravel.yml --profile "$APP_ENV" --env-file "$env_laravel"--env-file "$env_override" up --build -d
 
 }
 
@@ -1939,13 +1955,31 @@ ez_laravel_deploy_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        if [[ -z ${args['app_env']+x} ]]; then
+
+          args['app_env']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['app_env']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez laravel deploy APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['app_env']:-} ]] && [[ ! ${args['app_env']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "app_env must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
@@ -1983,13 +2017,31 @@ ez_laravel_start_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        if [[ -z ${args['app_env']+x} ]]; then
+
+          args['app_env']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['app_env']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez laravel start APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['app_env']:-} ]] && [[ ! ${args['app_env']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "app_env must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
@@ -2254,13 +2306,31 @@ ez_all_deploy_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        if [[ -z ${args['app_env']+x} ]]; then
+
+          args['app_env']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['app_env']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez all deploy APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['app_env']:-} ]] && [[ ! ${args['app_env']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "app_env must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
@@ -2298,13 +2368,31 @@ ez_all_start_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        if [[ -z ${args['app_env']+x} ]]; then
+
+          args['app_env']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['app_env']+x} ]]; then
+    printf "missing required argument: APP_ENV\nusage: ez all start APP_ENV\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['app_env']:-} ]] && [[ ! ${args['app_env']:-} =~ ^(test|staging|production)$ ]]; then
+    printf "%s\n" "app_env must be one of: test, staging, production" >&2
+    exit 1
+  fi
 
 }
 
@@ -2442,7 +2530,7 @@ ez_all_down_parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="0.1.0"
+  version="0.2.0"
   long_usage=''
   set -e
 
