:new: improved cloning now pulls (and removed build folders) instead of depth 1 clone if project was already cloned

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -856,6 +856,29 @@ inspect_args() {
 }
 
 # :command.user_lib
+# src/lib/copy_file.sh
+# Define a function for copying files and checking errors
+copy_file() {
+    local source_file=$1
+    local target_dir=$2
+    local target_file=$3
+
+    echo "Copying $source_file to $target_dir folder..."
+    if [ -f "$source_file" ]; then
+        cp "$source_file" "$target_dir/$target_file"
+        chmod +x "$target_dir/$target_file"
+
+        # Check if file copying was successful
+        if [ $? -ne 0 ]; then
+            echo "Error: Failed to copy $source_file."
+            exit 1
+        fi
+    else
+        echo "Error: $source_file not found."
+        exit 1
+    fi
+}
+
 # src/lib/merge_env.sh
 merge_env() {
   local file1="$1"
@@ -1012,44 +1035,50 @@ ez_laravel_deploy_command() {
 
   #careful with laravel_folder_name, it must be the same as laravel dockerfile and docker compose file
   laravel_folder_name="laravel"
-  echo "remove existing $laravel_folder_name folder..."
-  rm -rf "$laravel_folder_name"
 
-  git clone  --depth 1 -b "$GIT_BRANCH" "$GIT_URL" "$laravel_folder_name"
+  # Check if the folder exists
+  if [ -d "$laravel_folder_name" ]; then
+      echo "Updating existing $laravel_folder_name folder..."
+      cd "$laravel_folder_name" || exit 1
+      git pull origin "$GIT_BRANCH"
 
-  # Check if cloning was successful
-  if [ $? -ne 0 ]; then
-      echo "Error: Git cloning failed."
-      exit 1
-  fi
+      # Check if the git operation was successful
+      if [ $? -ne 0 ]; then
+          echo "Error: Git pull failed."
+          exit 1
+      fi
 
-  echo "copying entrypoint-builder.sh file to $laravel_folder_name folder..."
-  if [ -f "entrypoint-builder.sh" ]; then
-      cp "entrypoint-builder.sh" "$laravel_folder_name/entrypoint-builder.sh"
-      chmod +x "$laravel_folder_name/entrypoint-builder.sh"
+      echo "Remove previous build folders..."
+      rm -rf "node_modules" "vendor" "public/build"
+
+      # Check if the directory removal was successful
+      if [ $? -ne 0 ]; then
+          echo "Error: Failed to remove build folders."
+          exit 1
+      fi
+
+      cd - || exit 1
   else
-      echo "Error: entrypoint-builder.sh file not found."
-      exit 1
+      echo "Cloning new $laravel_folder_name folder..."
+      git clone --depth 1 -b "$GIT_BRANCH" "$GIT_URL" "$laravel_folder_name"
+
+      # Check if cloning was successful
+      if [ $? -ne 0 ]; then
+          echo "Error: Git cloning failed."
+          exit 1
+      fi
   fi
 
-  echo "copying .env file to $laravel_folder_name folder..."
-  if [ -f ".env" ]; then
-      cp ".env" "$laravel_folder_name/.env"
-  else
-      echo "Error: .env file not found."
-      exit 1
-  fi
+  # Copy necessary files to the Laravel folder
+  copy_file ".env" "$laravel_folder_name" ".env"
+  copy_file "entrypoint-builder.sh" "$laravel_folder_name" "entrypoint-builder.sh"
+  copy_file "entrypoint-laravel.sh" "$laravel_folder_name" "entrypoint-laravel.sh"
 
-  echo "copying entrypoint-laravel.sh file to $laravel_folder_name folder..."
-  if [ -f "entrypoint-laravel.sh" ]; then
-      cp "entrypoint-laravel.sh" "$laravel_folder_name/entrypoint-laravel.sh"
-      chmod +x "$laravel_folder_name/entrypoint-laravel.sh"
-  else
-      echo "Error: entrypoint-laravel.sh file not found."
-      exit 1
-  fi
-
+  # Run Docker Compose
+  echo "Running Docker Compose for builder..."
   docker compose -f compose-builder.yml up --build
+
+  echo "Running Docker Compose for Laravel in detached mode..."
   docker compose -f compose-laravel.yml up --build -d
 
 }
