:new: WIP ask_question

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -2120,18 +2120,18 @@ before_hook() {
   fi
 
   #TODO improve here i have duplication in app_env arg and APP_ENV in .env files
-  log_header "Reading .env files"
-  load_env "env/.env"
-  load_env "env/shared.env"
+  #log_header "Reading .env files"
+  #load_env "env/.env"
+  #load_env "env/shared.env"
 
-  if [[ -n "${args[APP_ENV]}" ]]; then
-    load_env "env/${args[APP_ENV]}.env"
-  fi
+  #if [[ -n "${args[APP_ENV]}" ]]; then
+  #  load_env "env/${args[APP_ENV]}.env"
+  #fi
 
-  if [[ "$APP_ENV" != "${args[APP_ENV]}" ]]; then
-      log_error "Error: APP_ENV in 'env/${args[APP_ENV]}.env' does not match 'ez' command argument ('$APP_ENV'!='${args[APP_ENV]}')."
-      exit 1
-  fi
+  #if [[ "$APP_ENV" != "${args[APP_ENV]}" ]]; then
+  #    log_error "Error: APP_ENV in 'env/${args[APP_ENV]}.env' does not match 'ez' command argument ('$APP_ENV'!='${args[APP_ENV]}')."
+  #    exit 1
+  #fi
 
 }
 
