:arrow_up_small: now warning also uses stderr

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -1080,7 +1080,7 @@ log_success() {
 # src/lib/log_warning.sh
 log_warning() {
   if [ "$#" -ne 1 ]; then
-      echo -e "\nInvalid Arguments, Usage: $0 <message>\n"
+      echo -e "\nInvalid Arguments, Usage: $0 <message>\n" >&2
       return 1
   fi
 
