:arrow_up_small: adjusted accessibility and privileges for new db and user

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -897,7 +897,7 @@ create_new_database_and_user() {
   NEW_USER_NAME=$2
   NEW_USER_PASSWORD=$3
 
-  echo -e "\n==[ Creating Database: $NEW_DB_NAME with User: $NEW_USER_NAME ]==\n"
+  log_header "Creating Database: $NEW_DB_NAME with User: $NEW_USER_NAME"
 
   MYSQL_USER="root"
   # DB_ROOT_PASSWORD is read from shared.env
@@ -906,27 +906,86 @@ create_new_database_and_user() {
   if ! docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "SELECT 1 FROM \`$NEW_DB_NAME\`;" > /dev/null 2>&1; then
     # Create database
     if ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS \`$NEW_DB_NAME\`;"; then
-      echo -e "\n==[ ERROR: Failed to create database '$NEW_DB_NAME'. ]==\n"
+      log
+      log_error "Failed to create database '$NEW_DB_NAME'"
       return 1
     fi
-    echo -e "\n==[ Created Database: $NEW_DB_NAME ]==\n";
+    log_success "Created Database: $NEW_DB_NAME";
   else
-    echo -e "\n==[ Database: $NEW_DB_NAME Already Exists ]==\n";
+    log "Database: $NEW_DB_NAME Already Exists";
+  fi
+
+  PMA_CONTAINER_NAME="pma"
+  if [[ "$APP_ENV" = "test" ]]; then
+    PMA_CONTAINER_NAME="pma-test"
   fi
 
   # Check if user exists (improve error handling)
   if ! docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "SELECT user FROM mysql.user WHERE user='$NEW_USER_NAME';" --skip-column-names -B | grep -q "$NEW_USER_NAME"; then
     # Create user and grant privileges
-    if ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "CREATE USER '$NEW_USER_NAME'@'%' IDENTIFIED BY '$NEW_USER_PASSWORD';" || \
-       ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON \`$NEW_DB_NAME\`.* TO '$NEW_USER_NAME'@'%';" || \
+    if ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "CREATE USER '$NEW_USER_NAME'@'localhost' IDENTIFIED BY '$NEW_USER_PASSWORD';" || \
+       ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "CREATE USER '$NEW_USER_NAME'@'$PMA_CONTAINER_NAME' IDENTIFIED BY '$NEW_USER_PASSWORD';" || \
+       ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "CREATE USER '$NEW_USER_NAME'@'$DB_ROOT_PASSWORD' IDENTIFIED BY '$LARAVEL_CONTAINER_NAME';" || \
+       ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON \`$NEW_DB_NAME\`.* TO '$NEW_USER_NAME'@'localhost';" || \
+       ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON \`$NEW_DB_NAME\`.* TO '$NEW_USER_NAME'@'$PMA_CONTAINER_NAME';" || \
+       ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON \`$NEW_DB_NAME\`.* TO '$NEW_USER_NAME'@'$LARAVEL_CONTAINER_NAME';" || \
        ! sudo docker exec -i $DB_HOST mysql -u$MYSQL_USER -p$DB_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"; then
-      echo -e "\n==[ ERROR: Failed to create and grant privileges for user '$NEW_USER_NAME'. ]==\n"
+      log_error "Failed to create and grant privileges for user '$NEW_USER_NAME'"
       return 1
     fi
-    echo -e "\n==[ User: '$NEW_USER_NAME' created for DB: $NEW_DB_NAME with full privileges ]==\n";
+    log_success -e "User: '$NEW_USER_NAME' created for DB: $NEW_DB_NAME with full privileges";
   else
-    echo -e "\n==[ User '$NEW_USER_NAME' already exists. ]==\n";
+    log "User '$NEW_USER_NAME' already exists";
   fi
+}
+
+# src/lib/log.sh
+log() {
+  if [ "$#" -ne 1 ]; then
+      echo -e "\nInvalid Arguments, Usage: $0 <message>\n"
+      return 1
+  fi
+
+  echo "-- $1"
+}
+
+# src/lib/log_error.sh
+log() {
+  if [ "$#" -ne 1 ]; then
+      echo -e "\nInvalid Arguments, Usage: $0 <message>\n"
+      return 1
+  fi
+
+  RED='\033[0;31m'
+  NORMAL='\033[0m'
+
+  echo "${RED}-- $1${NORMAL}"
+}
+
+# src/lib/log_header.sh
+log_header() {
+  if [ "$#" -ne 1 ]; then
+      echo -e "\nInvalid Arguments, Usage: $0 <message>\n"
+      return 1
+  fi
+
+  BOLD_CYAN='\033[1;36m'
+  NORMAL='\033[0m'
+
+  echo -e "${BOLD_CYAN}==[ $1 ]==\n${NORMAL}"
+}
+
+# src/lib/log_success.sh
+log() {
+  if [ "$#" -ne 1 ]; then
+      echo -e "\nInvalid Arguments, Usage: $0 <message>\n"
+      return 1
+  fi
+
+  GREEN='\033[0;32m'
+  NORMAL='\033[0m'
+
+  echo "${GREEN}-- $1${NORMAL}"
 }
 
 # src/lib/merge_env.sh
